source 'http://rubygems.org'
gem 'mechanize'
gem 'tweetstream'
gem 'bson_ext'
gem 'mongo'
gem 'xml-simple', :require => 'xmlsimple'
gem 'dm-mongo-adapter', :git => 'git://github.com/solnic/dm-mongo-adapter.git'
gem 'dm-core', :git => 'git://github.com/datamapper/dm-core.git'
gem 'dm-aggregates', :git => 'git://github.com/datamapper/dm-aggregates.git'
gem 'dm-do-adapter', :git => 'git://github.com/datamapper/dm-do-adapter.git'
gem 'dm-migrations', :git => 'git://github.com/datamapper/dm-migrations.git'
gem 'dm-serializer', :git => 'git://github.com/datamapper/dm-serializer.git'
gem 'dm-timestamps', :git => 'git://github.com/datamapper/dm-timestamps.git'
gem 'dm-transactions', :git => 'git://github.com/datamapper/dm-transactions.git'
gem 'dm-types', :git => 'git://github.com/datamapper/dm-types.git'
gem 'dm-validations', :git => 'git://github.com/datamapper/dm-validations.git'
